
server:
  port: 9090
  
spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:8086
  cloud:
    gateway:
      routes:
      - id: ORDER-SERVICE
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/order/**
        filters:
          - name: CircuitBreaker
            args:
              name: ORDER-SERVICE
              fallbackuri: forward:/orderServiceFallBack
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 1
      - id: PAYMENT-SERVICE
        uri: lb://PAYMENT-SERVICE
        predicates:
        - Path=/payment/**
        filters:
          - name: CircuitBreaker
            args:
              name: PAYMENT-SERVICE
              fallbackuri: forward:/paymentServiceFallBack
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 1
      - id: PRODUCT-SERVICE
        uri: lb://PRODUCT-SERVICE
        predicates:
        - Path=/product/**
        filters:
          - name: CircuitBreaker
            args:
              name: PRODUCT-SERVICE
              fallbackuri: forward:/productServiceFallBack
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 1
            
okta:
  oauth2:
    issuer: https://dev-73707689.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaawjpwdlqWqvpTn5d7
    client-secret: grMT9mfEy4CWfcEgak1LzKW6bFZnsQPxn7AB-CjR7kjgSFQiavq4kG3KKa9bNKvp
    scopes: openid, profile, email, offline_access
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            